# Generated by Django 3.1.1 on 2020-09-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='userid',
            field=models.CharField(max_length=10),
        ),
    ]
